# Generated by Django 4.2.7 on 2025-06-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('description', models.TextField(blank=True, help_text='模板描述', null=True)),
                ('graph_json', models.JSONField(blank=True, help_text='networkx图的JSON表示（通过business_flow.utils生成）', null=True)),
                ('executed_targets', models.JSONField(blank=True, help_text='执行过的任务目标（包含targetnode和targetsequence）', null=True)),
                ('map', models.ForeignKey(help_text='关联地图', on_delete=django.db.models.deletion.RESTRICT, related_name='templates', to='resourcedb.map')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'db_table': 'Template',
            },
        ),
    ]
