# Generated by Django 4.2.7 on 2025-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcedb', '0002_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='map_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='technique_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
