# Generated by Django 4.2.7 on 2025-06-11 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcedb', '0003_template_map_info_template_technique_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resourcedb.technique'),
        ),
    ]
