# Generated by Django 4.2.7 on 2025-06-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcedb', '0004_template_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='map',
            field=models.ForeignKey(blank=True, help_text='关联地图', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='templates', to='resourcedb.map'),
        ),
    ]
