---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator-sa  # 自定义服务账户名
  namespace: your-namespace  # 替换为实际命名空间


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator-role
rules:
- apiGroups: [""]  # 核心API组（Pod属于此类）
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]  # Deployment属于此类（若通过Deployment创建Pod）
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-creator-binding
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: your-namespace
roleRef:
  kind: ClusterRole
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io