# Generated by Django 5.2.1 on 2025-06-18 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerinstance',
            name='max_connections',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大连接数'),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20, verbose_name='警报级别')),
                ('trigger_condition', models.TextField(verbose_name='触发条件')),
                ('message', models.TextField(verbose_name='警报消息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='触发时间')),
                ('rule_type', models.CharField(choices=[('container_cpu', '容器CPU使用率'), ('container_memory', '容器内存使用率'), ('route_latency', '路由延迟'), ('instance_health', '实例健康状态')], max_length=20, verbose_name='规则类型')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('container_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='userdb.containerinstance', verbose_name='关联容器实例')),
            ],
            options={
                'verbose_name': '监控警报规则',
                'verbose_name_plural': '监控警报规则',
                'db_table': 'alert_rules',
                'indexes': [models.Index(fields=['container_instance', 'level'], name='alert_rules_contain_cf9dcd_idx'), models.Index(fields=['is_active', 'created_at'], name='alert_rules_is_acti_ac27cd_idx')],
            },
        ),
    ]
