apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        # 这个名称来自 Prometheus Adapter 的转换规则
        name: django_http_requests_per_second
      target:
        type: AverageValue
        # 目标值: 每个 Pod 平均处理 100 RPS
        averageValue: "100"